export const QUESTIONS_PAGE = 'QUESTIONS_PAGE';

export const TAGS_PAGE = 'TAGS_PAGE';

export const ANSWER_QUESTION_PAGE = 'ANSWER_QUESTIONS_PAGE';

export const POST_QUESTION_PAGE = 'POST_QUESTIONS_PAGE';

export const POST_ANSWER_PAGE = 'POST_ANSWER_PAGE';

export const NEWEST_FILTER = 'NEWEST_FILTER';

export const ACTIVE_FILTER = 'ACTIVE_FILTER';

export const UNANSWERED_FILTER = 'UNANSWERED_FILTER';

export const SEARCH_FILTER = 'SEARCH_FILTER';

export const SEE_ANSWERS_PAGE = 'SEE_ANSWERS_PAGE';

export const SPLASH_PAGE = 'SPLASH_PAGE';

export const LOGIN_PAGE = 'LOGIN_PAGE';

export const REGISTER_PAGE = 'REGISTER_PAGE';

export const USER_PROFILE = 'USER_PROFILE'

export const MODIFY_QUESTION_PAGE = 'MODIFY_QUESTION_PAGE'